### ISSUE TITLE
config json file

### ISSUE THREAD

**Issue by BestSonny** [skyoung/MemTrack#2]
@skyoung  Thank you for the work. Is it possible for you to provide scripts for generating the cfg.json for all the datasets? I can not run your demo with the following error:
```
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    run_tracker()
  File "demo.py", line 93, in run_tracker
    seq = load_seq_config('Basketball')
  File "demo.py", line 55, in load_seq_config
    configFile = open(src)
```

**Comment by vodp** [comment]
Hi @skyoung , can you update the repo so that the demo can run out of the box? At the moment it requires preset config of some dataset and that one is not shipped with the code.

**Comment by BestSonny** [comment]
@skyoung  I guess you haven't uploaded the json files yet.

**Comment by skyoung** [comment]
No need json file now. Please check the new demo file.

**Comment by BestSonny** [comment]
@skyoung Thank you very much. It is now working.

**Comment by vodp** [comment]
Correct me if I am wrong, but I cannot run the demo yet, it requires `groundtruth_rect.txt` as in the following code
```
def load_seq_config(seq_name):
    src = os.path.join(config.otb_data_dir,seq_name,'groundtruth_rect.txt')
```

**Comment by skyoung** [comment]
`groundtruth_rect.txt` is provided by OTB dataset already.
